apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-hello-world
  template:
    metadata:
      labels:
        app: django-hello-world
    spec:
      containers:
      - name: django-hello-world
        image: asia-south1-docker.pkg.dev/sample-427910/pocs/django-hello-world:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_password
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: instance_connection_name
      initContainers:
        - name: migrate-job
          image: asia-south1-docker.pkg.dev/sample-427910/pocs/django-hello-world:latest
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: instance_connection_name
          command: ["python", "manage.py", "migrate"]

---
apiVersion: v1 
kind: Service
metadata:
  name: django-hello-world-service
spec:
  selector:
    app: django-hello-world
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30961
  type: NodePort
  