name: Django-Hello-World CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v1
    - name: Login to GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Configure docker with GCP
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
    - name: github_build_number
      shell: bash
      run: |
          pwd
          echo "${{github.run_number}}"

    - name: Build Django-hello-world
      run: |
        docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/pocs/django-hello-world:latest .

    - name: Push Django-hello-world to GCP artifactory
      run: |
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/pocs/django-hello-world:latest
