name: Django-Hello-World CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v1
    - name: Login to GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Configure docker with GCP
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build Django-hello-world
      run: |
        docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/pocs/django-hello-world:temp .

    - name: Create and push Git tag
      id: tag_step
      if: success()
      run: |
        TAG="v1.0.${{ github.run_number }}"
        git tag $TAG
        git push origin $TAG
        echo "::set-output name=tag::$TAG"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag Django-Hello-World build
      run: |
        docker tag asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/pocs/django-hello-world:temp asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/pocs/django-hello-world:${{ steps.tag_step.outputs.tag }}

    - name: Push Django-hello-world to GCP artifactory
      run: |
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/pocs/django-hello-world:${{ steps.tag_step.outputs.tag }}
    

