name: Deploy to GKE

on:
  workflow_dispatch: # Triggered on-demand

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials sample --zone asia-south1-a --project ${{ secrets.GCP_PROJECT }}

    - name: Fetch DB_NAME secret
      id: get-db-name
      run: echo "::set-output name=db_name::$(gcloud secrets versions access latest --secret=dev-db_name)"

    - name: Fetch DB_USER secret
      id: get-db-user
      run: echo "::set-output name=db_user::$(gcloud secrets versions access latest --secret=dev-db_user)"

    - name: Fetch DB_PASSWORD secret
      id: get-db-password
      run: echo "::set-output name=db_password::$(gcloud secrets versions access latest --secret=dev-db_pw)"

    - name: Fetch INSTANCE_CONNECTION_NAME secret
      id: get-instance-connection-name
      run: echo "::set-output name=instance_connection_name::$(gcloud secrets versions access latest --secret=dev-db_instance_ip)"

    - name: Create Kubernetes secrets
      run: |
        kubectl create secret generic db-credentials \
          --from-literal=db_name=${{ steps.get-db-name.outputs.db_name }} \
          --from-literal=db_user=${{ steps.get-db-user.outputs.db_user }} \
          --from-literal=db_password=${{ steps.get-db-password.outputs.db_password }} \
          --from-literal=instance_connection_name=${{ steps.get-instance-connection-name.outputs.instance_connection_name }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to GKE
      run: kubectl apply -f deployment.yaml
